name: Publish Runner Image

on:
  push:
    branches:
    - main

env:
  IMAGE_NAME: iaas/actions-runner

jobs:
  actions-runner:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.runner.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Runner Version
        id: runner
        run: |
          from_file="$(cat runners/Containerfile |
            sed -En '/ARG\s+RUNNER_VERSION/ { s/ARG\s+RUNNER_VERSION=//; p; }')"
          echo "version=$from_file" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.runner.outputs.version }}
            type=raw,value=latest,enable=true
            type=sha

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v4
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v7
        with:
          file: runners/Containerfile
          context: ./runners
          push: true
          tags: ${{ steps.meta.outputs.tags }}
